# Generated by Django 4.2.1 on 2023-07-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventdata_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='club_name',
        ),
    ]
