# Generated by Django 4.2.1 on 2023-07-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_eventdata_club_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdata',
            old_name='collaborater',
            new_name='collaborator',
        ),
    ]
