# Generated by Django 4.2.1 on 2023-07-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_collaborater_eventdata_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='collaborator',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_venue',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
