# Generated by Django 4.2.1 on 2023-07-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_eventdata_collaborator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='token_price',
        ),
    ]
