# Generated by Django 4.2.1 on 2023-07-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_eventdata_token_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='token_price',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
