# Generated by Django 4.2.1 on 2023-07-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventdata_event_desc_eventdata_flyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='text_chart',
        ),
        migrations.AddField(
            model_name='eventdata',
            name='table_chart',
            field=models.ImageField(default='0', upload_to='Table_Chart'),
            preserve_default=False,
        ),
    ]
