# Generated by Django 4.2.1 on 2023-07-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_eventdata_text_chart_eventdata_table_chart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdata',
            old_name='hosts',
            new_name='host',
        ),
    ]
