# Generated by Django 4.2.1 on 2023-07-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_rename_hosts_eventdata_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='user_id',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
