# Generated by Django 4.2.1 on 2023-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_eventdata_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='event_date_alt',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='event_time_alt',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
