# Generated by Django 4.2.1 on 2023-07-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('his_first_name', models.CharField(max_length=255)),
                ('his_last_name', models.CharField(max_length=255)),
                ('his_number', models.CharField(max_length=12)),
                ('her_first_name', models.CharField(max_length=255)),
                ('her_last_name', models.CharField(max_length=255)),
                ('her_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=255)),
                ('user_qr', models.ImageField(upload_to='couple')),
            ],
        ),
        migrations.CreateModel(
            name='Stag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=12)),
                ('user_qr', models.ImageField(upload_to='stag')),
            ],
        ),
    ]
