# Generated by Django 4.2.1 on 2023-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='event_id',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stag',
            name='event_id',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
