# Generated by Django 4.2.1 on 2023-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_data', '0004_clubs_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('acc_type', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('club_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(default='Null', max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('instagram_link', models.CharField(default='Null', max_length=255)),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=12)),
                ('logo', models.ImageField(upload_to='Logos')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Clubs_Company',
        ),
    ]
