# Generated by Django 4.2.1 on 2023-07-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_data', '0005_club_company_delete_clubs_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stag',
            name='entered',
            field=models.BooleanField(default=False),
        ),
    ]
