# Generated by Django 4.2.1 on 2023-06-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_number', models.CharField(max_length=20)),
                ('user_pass_qty', models.CharField(max_length=2)),
                ('user_qr', models.ImageField(upload_to='user_qrs')),
            ],
        ),
    ]
