# Generated by Django 4.2.1 on 2023-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(default='0', max_length=4),
            preserve_default=False,
        ),
    ]
