# Generated by Django 4.2.1 on 2023-07-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_userdata_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='payment_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
